# Generated by Django 4.0 on 2022-01-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
